-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 19:04:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL,
  `shelf life` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_in_recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_in_recipe` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_product_in_recipe_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_in_recipe_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `difficult` INT NOT NULL,
  `product_in_recipe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_in_recipe_id`),
  INDEX `fk_recipe_product_in_recipe1_idx` (`product_in_recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_product_in_recipe1`
    FOREIGN KEY (`product_in_recipe_id`)
    REFERENCES `mydb`.`product_in_recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dish` (
  `id_dish` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `count` INT NULL,
  `price` DECIMAL(10) NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`id_dish`, `recipe_id`),
  INDEX `fk_dish_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_dish_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurant` (
  `id` INT NOT NULL,
  `ratings` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `opening_hours` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT NOT NULL,
  `total_score` DECIMAL(10) NOT NULL,
  `customer_name` VARCHAR(100) NULL,
  `dish_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`, `dish_id`, `restaurant_id`),
  INDEX `fk_order_dish_idx` (`dish_id` ASC) VISIBLE,
  INDEX `fk_order_restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_dish`
    FOREIGN KEY (`dish_id`)
    REFERENCES `mydb`.`dish` (`id_dish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `mydb`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country_producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country_producer` (
  `id` INT NOT NULL,
  `country_producer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone` (
  `id` INT NOT NULL,
  `model_phone` VARCHAR(45) NOT NULL,
  `country_producer_id` INT NOT NULL,
  `cost` DECIMAL(10) NULL,
  `phonecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `country_producer_id`),
  INDEX `fk_phone_country_producer1_idx` (`country_producer_id` ASC) VISIBLE,
  CONSTRAINT `fk_phone_country_producer1`
    FOREIGN KEY (`country_producer_id`)
    REFERENCES `mydb`.`country_producer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`view_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_service` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sum` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service_center` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_service` (
  `id` INT NOT NULL,
  `view_service_id` INT NOT NULL,
  `service_center_id` INT NOT NULL,
  `warranty` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `view_service_id`, `service_center_id`),
  INDEX `fk_service_view_service1_idx` (`view_service_id` ASC) VISIBLE,
  INDEX `fk_customer_service_service_center1_idx` (`service_center_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_view_service1`
    FOREIGN KEY (`view_service_id`)
    REFERENCES `mydb`.`view_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_service_service_center1`
    FOREIGN KEY (`service_center_id`)
    REFERENCES `mydb`.`service_center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `sum` INT NOT NULL,
  `customer_service_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`id`, `customer_service_id`, `client_id`, `phone_id`),
  INDEX `fk_payment_customer_service1_idx` (`customer_service_id` ASC) VISIBLE,
  INDEX `fk_payment_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_payment_phone1_idx` (`phone_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_customer_service1`
    FOREIGN KEY (`customer_service_id`)
    REFERENCES `mydb`.`customer_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_phone1`
    FOREIGN KEY (`phone_id`)
    REFERENCES `mydb`.`phone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
